# Generated by Django 5.1.4 on 2024-12-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='photo_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='video_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
