# Generated by Django 5.1.4 on 2024-12-17 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default='dharshini@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
