# Generated by Django 5.1.4 on 2024-12-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_created_at_login_email_login_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='login',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
