# Generated by Django 5.1.4 on 2024-12-18 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_login_created_at_remove_login_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
