# Generated by Django 5.1.4 on 2024-12-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_media',
            name='photo_urls',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store_media',
            name='video_urls',
            field=models.URLField(blank=True, null=True),
        ),
    ]
