# Generated by Django 5.1.4 on 2024-12-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_store_media_photo_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_media',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
